### ISSUE TITLE
Unable to locate theo25/llvm-verified-backend dependecy

### ISSUE THREAD

**Issue by mewmew** [kframework/X86-64-semantics#1]
Hi Sandeep,

Thanks for releasing this project to the open source community! I tried to get up and running, but failed to locate one of the dependencies.

https://github.com/theo25/llvm-verified-backend lists 404.

Wish you a most lovely start of the new year :)

Kindly,
Robin Eklind

**Comment by sdasgup3** [comment]
Dear Robin,
I am sorry that the aforementioned project is private and hence inaccessible. X86 semantics need a portion of that project which serves as a common memory model interface which is shared by both  X86 and LLVM semantics and I believe the common interface could be made public. I will talk with the owner are get back to you asap.

**Comment by mewmew** [comment]
>  I am sorry that the aforementioned project is private and hence inaccessible. X86 semantics need a portion of that project which serves as a common memory model interface which is shared by both X86 and LLVM semantics and I believe the common interface could be made public. I will talk with the owner are get back to you asap.

Thank you! X86 semantics seems like a tremendously useful project, and it would be great to get it up and running with dependencies and such.

Cheers,
Robin

**Comment by sdasgup3** [comment]
Dear Robin (@mewmew),
Can you please try the master branch now? I made a quick fix by copying the relevant K modules.  
Regards,
Sandeep

**Comment by mewmew** [comment]
Hi Sandeep!

Thanks! I'll try the master branch. I tried to get K up and running, but bumped into this issue https://github.com/kframework/k/issues/256

Cheers,
Robin

**Comment by sdasgup3** [comment]
@mewmew  Closing this issue for now. Please feel free to reopen it. The above issue is related to K framework and should have been fixed by now.
