### ISSUE TITLE
Unable to compile the x86-64 semantics

### ISSUE THREAD

**Issue by yuzeng2333** [kframework/X86-64-semantics#6]
Hi, I have an issue with compiling the x86-64 semantics. I am using Ubuntu 16.04.6. I have double checked that I have installed all the prerequisites. That is to say, I have run the following commands successfully:
`git submodule update --init --recursive`
`sudo apt-get install build-essential m4 openjdk-8-jdk libgmp-dev libmpfr-dev pkg-config flex z3 libz3-dev maven opam python3 cmake gcc clang-8 lld-8 llvm-8-tools zlib1g-dev bison libboost-test-dev libyaml-dev libjemalloc-dev`
`llvm-backend/src/main/native/llvm-backend/install-rust`
`curl -sSL https://get.haskellstack.org/ | sh`

After run 'mvn package', all are successful. But when I try to compile with x86 semantics with the following commands, errors are reported
`cd X86-semantics/semantics`
`../scripts/kompile.pl --backend java`

The output for compiling x86 semantics is attached. Thanks for your attention!
[compile-x86-error-info.txt](https://github.com/kframework/X86-64-semantics/files/3418190/compile-x86-error-info.txt)
@sdasgup3

**Comment by sdasgup3** [comment]
Hi @hotzeng It seems that you have not pulled the latest master branch of the X86-64-semantics repository. Please try that.

This is evident from the log file where you get the error at line [289](https://github.com/kframework/X86-64-semantics/blob/master/semantics/common/library/common-c-library-io.k#L289), which is already fixed now

**Comment by yuzeng2333** [comment]
It is fixed. Thank you!
